### ISSUE TITLE
ImportError: No module named autosub

### ISSUE THREAD

**Issue by shashaanktulsyan** [agermanidis/autosub#11]
I installed autosub on windows, with python27 to c:\Python27\Scripts\
I run it with the following command.
But while doing so I get many errors while the program tries to fork new instances of itself.

How to fix this?

Batch Script
```batch
@echo off
SET PATH=%PATH%;P:\utilities\MeGUI_2418_x86\tools\ffmpeg\
SET PATH=%PATH%;c:\Python27\Scripts\
c:
cd\Python27\Scripts\
c:\Python27\python.exe autosub "theaudioinput.mp3"
```
Output
```python
	Traceback (most recent call last):
	C  File "<string>", line 1, in <module>
	  File "c:\Python27\lib\multiprocessing\forking.py", line 380, in main--:--:--
	    prepare(preparation_data)
	  File "c:\Python27\lib\multiprocessing\forking.py", line 489, in prepare
	    file, path_name, etc = imp.find_module(main_name, dirs)
	ImportError: No module named autosub
	Traceback (most recent call last):
	  File "<string>", line 1, in <module>
	  File "c:\Python27\lib\multiprocessing\forking.py", line 380, in main
	    prepare(preparation_data)
	  File "c:\Python27\lib\multiprocessing\forking.py", line 489, in prepare
	    file, path_name, etc = imp.find_module(main_name, dirs)
	ImportError: No module named autosub
	Traceback (most recent call last):
	  File "<string>", line 1, in <module>
	  File "c:\Python27\lib\multiprocessing\forking.py", line 380, in main
	    prepare(preparation_data)
	  File "c:\Python27\lib\multiprocessing\forking.py", line 489, in prepare
	    file, path_name, etc = imp.find_module(main_name, dirs)
	ImportError: No module named autosub
	Traceback (most recent call last):
	  File "<string>", line 1, in <module>
	  File "c:\Python27\lib\multiprocessing\forking.py", line 380, in main
	    prepare(preparation_data)
	  File "c:\Python27\lib\multiprocessing\forking.py", line 489, in prepare
	    file, path_name, etc = imp.find_module(main_name, dirs)
	ImportError: No module named autosub
	Traceback (most recent call last):
	  File "<string>", line 1, in <module>
	  File "c:\Python27\lib\multiprocessing\forking.py", line 380, in main
	    prepare(preparation_data)
	Traceback (most recent call last):
	  File "<string>", line 1, in <module>
	  File "c:\Python27\lib\multiprocessing\forking.py", line 380, in main
	    prepare(preparation_data)
	  File "c:\Python27\lib\multiprocessing\forking.py", line 489, in prepare
	    file, path_name, etc = imp.find_module(main_name, dirs)
	ImportError: No module named autosub
	Traceback (most recent call last):
	  File "<string>", line 1, in <module>
	  File "c:\Python27\lib\multiprocessing\forking.py", line 380, in main
	    prepare(preparation_data)
	  File "c:\Python27\lib\multiprocessing\forking.py", line 489, in prepare
	    file, path_name, etc = imp.find_module(main_name, dirs)
	ImportError: No module named autosub
	Traceback (most recent call last):
	  File "c:\Python27\lib\multiprocessing\forking.py", line 489, in prepare
	  File "<string>", line 1, in <module>
	      File "c:\Python27\lib\multiprocessing\forking.py", line 380, in main
	file, path_name, etc = imp.find_module(main_name, dirs)
	    ImportErrorprepare(preparation_data)
	:   File "c:\Python27\lib\multiprocessing\forking.py", line 489, in prepar
```

**Comment by indextbag** [comment]
me too please

**Comment by owbeg** [comment]
It is due to implementation multiprocessing on Windows platform. Try to rename <PYTHON_PATH>\Scripts\autosub to (for example) <PYTHON_PATH>\Scripts\autosub_app.py
(renaming to autosub.py is not enough)
