### ISSUE TITLE
Read time out on large WAV files

### ISSUE THREAD

**Issue by avibagla** [agermanidis/autosub#117]
I'm using autosub to generate an SRT on a couple large SRT files, but I keep running into this error:

```
Traceback (most recent call last):% |####                        | ETA:  0:06:40
  File "~/anaconda/bin/autosub", line 304, in <module>
    sys.exit(main())
  File "~/anaconda/bin/autosub", line 252, in main
    for i, transcript in enumerate(pool.imap(recognizer, extracted_regions)):
  File "~/anaconda/lib/python2.7/multiprocessing/pool.py", line 668, in next
    raise value
requests.exceptions.ReadTimeout: None: None 
```

Is it trying to hit the API too many times? Or is it just too big?

**Comment by niusijian** [comment]
i dont know。but i have a question，if i use this tool so many times， it will not work？would you understand，sorry my english is poor
