### ISSUE TITLE
Error with ffmpeg

### ISSUE THREAD

**Issue by marimemad** [agermanidis/autosub#118]
when trying to run it, is says:

C:\Users"NAME">C:\Python27\python.exe C:\Python27\scripts\autosub_app.p
y -S en -D en c:\"video name"
ffmpeg: Executable not found on machine.
Traceback (most recent call last):
File "C:\Python27\scripts\autosub_app.py", line 304, in 
sys.exit(main())
File "C:\Python27\scripts\autosub_app.py", line 230, in main
audio_filename, audio_rate = extract_audio(args.source_path)
File "C:\Python27\scripts\autosub_app.py", line 140, in extract_audio
raise Exception("Dependency not found: ffmpeg")
Exception: Dependency not found: ffmpeg

Although I have copied ffmpeg.exe in Python27 folder.
Any help?

**Comment by huangzaishoudu** [comment]
change all the ffmpeg in autosub_app.py to ffmpeg.exe

**Comment by andibakti** [comment]
To add detail to @huangzaishoudu 's answer, 
You only need to change this line
 `if not which("ffmpeg"):` 
to this 
`if not which("ffmpeg.exe"):`

**Comment by BingLingGroup** [comment]
I've already released the standalone version with ffmpeg dependency. Click [here](https://github.com/BingLingGroup/autosub/releases) and download.

**Comment by huanmingcn** [comment]
The most easy way is change the filename of ffmpeg.exe to ffmpeg.
