### ISSUE TITLE
Some Errors!  OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by perpi** [agermanidis/autosub#13]
I get this error:

autosub -F srt -S en-US -D en file.mp4 

     Traceback (most recent call last):
     File "/usr/local/bin/autosub", line 257, in <module>
     sys.exit(main())
     File "/usr/local/bin/autosub", line 193, in main
     audio_filename, audio_rate = extract_audio(args.source_path)
     File "/usr/local/bin/autosub", line 103, in extract_audio
     subprocess.check_output(command)
     File "/usr/lib/python2.7/subprocess.py", line 566, in check_output
     process = Popen(stdout=PIPE, *popenargs, **kwargs)
     File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
     errread, errwrite)
     File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
     raise child_exception
     OSError: [Errno 2] No such file or directory

I've installed iy by ‍‍‍‍‍‍‍‍‍‍‍‍‍'pip'

**Comment by agermanidis** [comment]
Have you installed ffmpeg?

**Comment by perpi** [comment]
Oops, Nope!
I installed it and now, it's working well.
`ffmpeg` is not available in Ubuntu 14.04; I installed it by a PPA!

Thanks for this awesome app; I already uploaded my videos to Youtube in order to download auto captions by youtube-dl. It was kind of a headache on big files!

**Comment by agermanidis** [comment]
No problem! Glad you're finding it helpful!
