### ISSUE TITLE
raise ResponseNotReady() httplib.ResponseNotReady  报这个错误是什么原因

### ISSUE THREAD

**Issue by maozicb** [agermanidis/autosub#145]
Converting speech regions to FLAC files: 100% |########################################################| Time:  0:00:03
Performing speech recognition: 100% |##################################################################| Time:  0:00:13
Traceback (most recent call last):
  File "C:\Python27\Scripts\autosub-script.py", line 11, in <module>
    load_entry_point('autosub==0.4.0', 'console_scripts', 'autosub')()
  File "c:\python27\lib\site-packages\autosub\__init__.py", line 413, in main
    output=args.output,
  File "c:\python27\lib\site-packages\autosub\__init__.py", line 288, in generate_subtitles
    src=src_language)
  File "c:\python27\lib\site-packages\autosub\__init__.py", line 125, in __init__
    developerKey=self.api_key)
  File "c:\python27\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "c:\python27\lib\site-packages\googleapiclient\discovery.py", line 224, in build
    requested_url, discovery_http, cache_discovery, cache, developerKey)
  File "c:\python27\lib\site-packages\googleapiclient\discovery.py", line 274, in _retrieve_discovery_doc
    resp, content = http.request(actual_url)
  File "c:\python27\lib\site-packages\httplib2\__init__.py", line 2135, in request
    cachekey,
  File "c:\python27\lib\site-packages\httplib2\__init__.py", line 1796, in _request
    conn, request_uri, method, body, headers
  File "c:\python27\lib\site-packages\httplib2\__init__.py", line 1737, in _conn_request
    response = conn.getresponse()
  File "c:\python27\lib\httplib.py", line 1108, in getresponse
    raise ResponseNotReady()
httplib.ResponseNotReady
安装的这个版本
https://github.com/BingLingGroup/autosub

**Comment by BingLingGroup** [comment]
安装的我的仓库里的版本请去我仓库里提issue，谢谢

**Comment by BingLingGroup** [comment]
看log感觉是网络问题，建议使用更稳定的梯子或者可连接至谷歌的服务器来解决问题。
