### ISSUE TITLE
socket.timeout: timed out

### ISSUE THREAD

**Issue by zhangxiang-1222** [agermanidis/autosub#150]
JJ@MacBook-Pro  autosub -S zh-CN -D en -K {Key} /Users/JJ/Desktop/1222.mp4
Converting speech regions to FLAC files: 100% |##################| Time: 0:00:01
Performing speech recognition: 100% |####################################################| Time: 0:01:55
Traceback (most recent call last):
  File "/usr/local/bin/autosub", line 304, in <module>
    sys.exit(main())
  File "/usr/local/bin/autosub", line 261, in main
    src=args.src_language)
  File "/usr/local/bin/autosub", line 95, in __init__
    developerKey=self.api_key)
  File "/usr/local/lib/python2.7/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/googleapiclient/discovery.py", line 224, in build
    requested_url, discovery_http, cache_discovery, cache, developerKey)
  File "/usr/local/lib/python2.7/site-packages/googleapiclient/discovery.py", line 274, in _retrieve_discovery_doc
    resp, content = http.request(actual_url)
  File "/usr/local/lib/python2.7/site-packages/httplib2/__init__.py", line 2135, in request
    cachekey,
  File "/usr/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1796, in _request
    conn, request_uri, method, body, headers
  File "/usr/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1701, in _conn_request
    conn.connect()
  File "/usr/local/lib/python2.7/site-packages/httplib2/__init__.py", line 1360, in connect
    sock.connect(sockaddr)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.timeout: timed out

autosub -S zh-CN -D zh-CN -K {Key} /Users/JJ/Desktop/1222.mp4   
zh-CN转zh-CN可以成功
zh-CN转 en 就报上面的错误 Error

**Comment by BingLingGroup** [comment]
不排除是translation api过于陈旧无法使用，我对translation api并没有进行过测试。可以考虑参考[我博客](https://binglinggroup.github.io/archives/autosub%E5%AE%89%E8%A3%85%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97(windows%E5%8F%8Aubuntu).html#%E8%87%AA%E5%8A%A8%E7%BF%BB%E8%AF%91%E5%8A%9F%E8%83%BD)中所说的几个他人魔改的可能可以使用免费翻译api的版本。
另外你需要确保你的终端加载了http/https代理，或者你的系统走了全局（虚拟网卡级别）的代理，或者换句话说你的终端可以连接到google服务器。

**Comment by zhangxiang-1222** [comment]
3Q ~ 已经解决！是终端链接不到google的原因。
