### ISSUE TITLE
What's the problem?

### ISSUE THREAD

**Issue by shechque** [agermanidis/autosub#16]
When I run 'pip install autosub' ,there is a error.
I use python3.5.1-amd64 & pip 8.0.2

Using cached progressbar-2.3.tar.gz
   Complete output from command python setup.py egg_info:
   Traceback (most recent call last):
     File "<string>", line 1, in <module>
     File "C:\Users\xxx\AppData\Local\Temp\pip-build-tl1gmkiv\progressbar\setu
.py", line 5, in <module>
       import progressbar
     File "C:\Users\xxx\AppData\Local\Temp\pip-build-tl1gmkiv\progressbar\prog
essbar\__init__.py", line 59, in <module>
       from progressbar.widgets import *
     File "C:\Users\xxx\AppData\Local\Temp\pip-build-tl1gmkiv\progressbar\prog
essbar\widgets.py", line 121, in <module>
       class FileTransferSpeed(Widget):
     File "c:\program files\python35\lib\abc.py", line 133, in __new__
       cls = super().__new__(mcls, name, bases, namespace)
   ValueError: 'format' in __slots__ conflicts with class variable
....

**Comment by namaljayathunga** [comment]
+1

**Comment by c2334867** [comment]
I am having the exact same problem. I am also using Python 3.5.1 on Windows 10 (64 bit). I can't seem to install Autosub but can install other things. I get the same ValueError: "'format' in __slots__ conflicts with class variable" message.

Any help would be appreciated!

**Comment by c2334867** [comment]
FYI - I was able to successfully install without these error messages by using Python 2.7 on a Windows 7 (64 bit) machine. Can't quite figure out how to run it, though

**Comment by ibrewster** [comment]
Looks like the problem is that the progress bar module isn't installing under python 3. Maybe that module isn't python 3 compatible?

**Comment by abolfazlsj** [comment]
I have an installation error with progressbar, too. if anybody solved please write solution. my error is : 

Command "python setup.py egg_info" failed with error code 1 in C:\Users\...\AppData\Local\Temp\pip-build-m3rr69d7\progressbar\

**Comment by johnomarkid** [comment]
+1. same error on my end. i tried with python 2.7 and python 3.5.

**Comment by Johndirr** [comment]
Since progressbar is not working with python3 could https://pypi.python.org/pypi/progressbar2 be added to setup.py instead?

**Comment by rybak** [comment]
Use pip with python2. autosub is not python3 compatible.

**Comment by JasmineChen** [comment]
I use this : pip2 install autosub 
to solve the problem and it now works well
