### ISSUE TITLE
requests.exceptions.ReadTimeout: None: None

### ISSUE THREAD

**Issue by levinyi** [agermanidis/autosub#162]
$ autosub -S en -D en test.subtitle.mp4
Converting speech regions to FLAC files: 100% |###############################################################################################################################################################################| Time: 0:00:03
Traceback (most recent call last):% |########################                                                                                                                                                                 | ETA:  5:44:33
  File "/cygene/software/annaconda2/bin/autosub", line 304, in <module>
    sys.exit(main())
  File "/cygene/software/annaconda2/bin/autosub", line 252, in main
    for i, transcript in enumerate(pool.imap(recognizer, extracted_regions)):
  File "/cygene/software/annaconda2/lib/python2.7/multiprocessing/pool.py", line 673, in next
    raise value
requests.exceptions.ReadTimeout: None: None

can anybody help?

**Comment by levinyi** [comment]
need a VPN for ubuntu?

**Comment by BingLingGroup** [comment]
> need a VPN for ubuntu?

@levinyi 这取决于你是在不能连接到google的机器上运行，还是可以连接到google的机器上运行。speech-to-text的api来自google，必须保证和google的连接通畅。

相关问题：#111

**Comment by levinyi** [comment]
我运行的这个机器不能google，汗
