### ISSUE TITLE
returned non-zero exit status 1

### ISSUE THREAD

**Issue by congmingyige** [agermanidis/autosub#196]
The problem is “returned non-zero exit status 1”
Using windows 10, install ffmpeg and add path.
similar questions: https://github.com/agermanidis/autosub/pull/74 https://github.com/agermanidis/autosub/issues/20

---

(py36_cgb) C:\Users\congm\Desktop\XXX>autosub -S fr -D zh-CN video.mp4
Output file #0 does not contain any stream
Traceback (most recent call last):
  File "C:\software\Anaconda3\envs\py36_cgb\Scripts\autosub-script.py", line 33, in <module>
    sys.exit(load_entry_point('autosub==0.4.0', 'console_scripts', 'autosub')())
  File "C:\software\Anaconda3\envs\py36_cgb\lib\site-packages\autosub\__init__.py", line 404, in main
    output=args.output,
  File "C:\software\Anaconda3\envs\py36_cgb\lib\site-packages\autosub\__init__.py", line 245, in generate_subtitles
    audio_filename, audio_rate = extract_audio(source_path)
  File "C:\software\Anaconda3\envs\py36_cgb\lib\site-packages\autosub\__init__.py", line 190, in extract_audio
    subprocess.check_output(command, stdin=open(os.devnull), shell=use_shell)
  File "C:\software\Anaconda3\envs\py36_cgb\lib\subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "C:\software\Anaconda3\envs\py36_cgb\lib\subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ffmpeg', '-y', '-i', 'video.mp4', '-ac', '1', '-ar', '16000', '-loglevel', 'error', 'C:\\Users\\congm\\AppData\\Local\\Temp\\tmpr2x_jqqi.wav']' returned non-zero exit status 1.

---

(py36_cgb) C:\Users\congm\Desktop\VITAE_Sylvie_Lorthois>where ffmpeg
C:\Program Files\ImageMagick-7.1.0-Q16-HDRI\ffmpeg.exe
C:\software\ImageMagick-7.0.10-Q16-HDRI\ffmpeg.exe
D:\software\ffmpeg-2021-12-06-git-ef00d40e32-full_build\bin\ffmpeg.exe

---

**Comment by gantoin** [comment]
You probably have a problem with your local FFmpeg, try to launch the printed command : 
```bash
ffmpeg -y -i video.mp4 -ac 1 -ar 16000 -loglevel error C:\Users\congm\AppData\Local\Temp\tmpr2x_jqqi.wav
```
You need probably some additional codecs or stuff like that.
