### ISSUE TITLE
Tried everything.

### ISSUE THREAD

**Issue by HakkaTjakka** [agermanidis/autosub#197]
Tried with python3 and python2
pip install git+https://github.com/agermanidis/autosub.git
pip2 install git+https://github.com/agermanidis/autosub.git
pip3 install git+https://github.com/agermanidis/autosub.git
sudo update-alternatives --config python
There are 2 choices for the alternative python (providing /usr/bin/python).
  Selection    Path              Priority   Status
------------------------------------------------------------
* 0            /usr/bin/python3   2         auto mode
  1            /usr/bin/python2   1         manual mode
  2            /usr/bin/python3   2         manual mode
Etc.
(On Ubuntu 20.04)

Still getting: 

(With Python3):
 File "/home/pacman/.local/bin/autosub", line 8, in <module>
    sys.exit(main())
  File "/home/pacman/.local/lib/python3.8/site-packages/autosub/__init__.py", line 397, in main
    subtitle_file_path = generate_subtitles(
  File "/home/pacman/.local/lib/python3.8/site-packages/autosub/__init__.py", line 247, in generate_subtitles
    regions = find_speech_regions(audio_filename)
  File "/home/pacman/.local/lib/python3.8/site-packages/autosub/__init__.py", line 198, in find_speech_regions
    reader = wave.open(filename)
  File "/usr/lib/python3.8/wave.py", line 510, in open
    return Wave_read(f)
  File "/usr/lib/python3.8/wave.py", line 164, in __init__
    self.initfp(f)
  File "/usr/lib/python3.8/wave.py", line 129, in initfp
    self._file = Chunk(file, bigendian = 0)
  File "/usr/lib/python3.8/chunk.py", line 63, in __init__
    raise EOFError
EOFError

(With Python2):
autosub -S en test.mp4
Traceback (most recent call last):
  File "/home/pacman/.local/bin/autosub", line 8, in <module>
    sys.exit(main())
  File "/home/pacman/.local/lib/python2.7/site-packages/autosub/__init__.py", line 404, in main
    output=args.output,
  File "/home/pacman/.local/lib/python2.7/site-packages/autosub/__init__.py", line 247, in generate_subtitles
    regions = find_speech_regions(audio_filename)
  File "/home/pacman/.local/lib/python2.7/site-packages/autosub/__init__.py", line 198, in find_speech_regions
    reader = wave.open(filename)
  File "/usr/lib/python2.7/wave.py", line 511, in open
    return Wave_read(f)
  File "/usr/lib/python2.7/wave.py", line 164, in __init__
    self.initfp(f)
  File "/usr/lib/python2.7/wave.py", line 129, in initfp
    self._file = Chunk(file, bigendian = 0)
  File "/usr/lib/python2.7/chunk.py", line 63, in __init__
    raise EOFError
EOFError

(Under windows it worked...)

(Sorry for the big font, dunno...)

**Comment by HakkaTjakka** [comment]
Got it working at last, thank you. Delete this issue

**Comment by HakkaTjakka** [comment]
Thank you again.
