### ISSUE TITLE
moov atom not found

### ISSUE THREAD

**Issue by bh4rtp** [agermanidis/autosub#20]
The details show as follow.

allen@allen-vm:~$ autosub -S en-GB -D zh-CN SimplySolar.mp4 
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x932caa0] moov atom not found
SimplySolar.mp4: Invalid data found when processing input
Traceback (most recent call last):
  File "/usr/local/bin/autosub", line 260, in <module>
    sys.exit(main())
  File "/usr/local/bin/autosub", line 194, in main
    audio_filename, audio_rate = extract_audio(args.source_path)
  File "/usr/local/bin/autosub", line 104, in extract_audio
    subprocess.check_output(command)
  File "/usr/lib/python2.7/subprocess.py", line 544, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['ffmpeg', '-y', '-i', 'SimplySolar.mp4', '-ac', '1', '-ar', '16000', '-loglevel', 'error', '/tmp/tmpdlIVEL.wav']' returned non-zero exit status 1

**Comment by kiemrong08** [comment]
You need to add the path of ffmpeg.exe (path of bin directory)  in drive to PATH variable environtment in windows.
