### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by Sopor-** [agermanidis/autosub#26]
I was trying to install autosub on Windows 8.1 but i did get this message:
```
pip install autosub
Collecting autosub
  Downloading autosub-0.3.8.tar.gz
Collecting google-api-python-client>=1.4.2 (from autosub)
  Downloading google_api_python_client-1.5.1-py2.py3-none-any.whl (50kB)
    100% |################################| 51kB 1.6MB/s
Requirement already satisfied (use --upgrade to upgrade): requests>=2.3.0 in c:\users\<user>\appdata\local\progr
ams\python\python35-32\lib\site-packages (from autosub)
Collecting pysrt>=1.0.1 (from autosub)
  Downloading pysrt-1.1.1.tar.gz (104kB)
    100% |################################| 112kB 6.6MB/s
Collecting progressbar>=2.3 (from autosub)
  Downloading progressbar-2.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\<user>\AppData\Local\Temp\pip-build-rjxli7ux\progressbar\setup.py", line 5, in <module>
        import progressbar
      File "C:\Users\<user>\AppData\Local\Temp\pip-build-rjxli7ux\progressbar\progressbar\__init__.py", line 59,
 in <module>
        from progressbar.widgets import *
      File "C:\Users\<user>\AppData\Local\Temp\pip-build-rjxli7ux\progressbar\progressbar\widgets.py", line 121,
 in <module>
        class FileTransferSpeed(Widget):
      File "c:\users\<user>\appdata\local\programs\python\python35-32\lib\abc.py", line 133, in __new__
        cls = super().__new__(mcls, name, bases, namespace)
    ValueError: 'format' in __slots__ conflicts with class variable

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\<user>\AppData\Local\Temp\pip-build-rjxl
i7ux\progressbar\
```
The reason i believe was python 3 so i tried python 2 instead and it seems to work but instead i now get this message when i try to run it:
```
python autosub
  File "autosub", line 252
    See --help for further information."
                                       ^
SyntaxError: Missing parentheses in call to 'print'
```
So i can't even get the help to show up :(

**Comment by peskdale** [comment]
No idea what the first error is caused by. Sorry.

The later syntax error you encountered happens when you run a python2 `print` command in python3. Double check which version you are indeed using, as it should not be possible to get that error in python2.

I note that there are no prerequisites for python mentioned in the documentation, despite providing a pip command for installation. Maybe something to add @agermanidis?

**Comment by Sopor-** [comment]
I manage to get autosub to run now but when it has extracted the wav file (tmpqslifb.wav) it went into a loop with this text. I can't even break it with CTRL+C...
```
ImportErrorTraceback (most recent call last):
          File "<string>", line 1, in <module>
: file, path_name, etc = imp.find_module(main_name, dirs)
Nfile, path_name, etc = imp.find_module(main_name, dirs)
  File "c:\Python27\lib\multiprocessing\forking.py", line 380, in main
ImportErroro module named autosubTraceback (most recent call last):
ImportError:
  File "<string>", line 1, in <module>
N:   File "c:\Python27\lib\multiprocessing\forking.py", line 380, in main
o module named autosub
    prepare(preparation_data)
  File "c:\Python27\lib\multiprocessing\forking.py", line 489, in prepare
    prepare(preparation_data)
  File "c:\Python27\lib\multiprocessing\forking.py", line 489, in prepare
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    file, path_name, etc = imp.find_module(main_name, dirs)
    ImportErrorfile, path_name, etc = imp.find_module(main_name, dirs)
:   File "c:\Python27\lib\multiprocessing\forking.py", line 380, in main
NImportErroro module named autosub:
No module named autosub
```
