### ISSUE TITLE
Issues With Installation

### ISSUE THREAD

**Issue by simonnarang** [agermanidis/autosub#48]
I am getting some errors with `progressbar` when installing:

```
$ python3 -m pip install autosub
Collecting autosub
  Using cached autosub-0.3.11.tar.gz
Collecting google-api-python-client>=1.4.2 (from autosub)
  Using cached google_api_python_client-1.6.1-py2.py3-none-any.whl
Collecting requests>=2.3.0 (from autosub)
  Using cached requests-2.12.4-py2.py3-none-any.whl
Collecting pysrt>=1.0.1 (from autosub)
  Using cached pysrt-1.1.1.tar.gz
Collecting progressbar>=2.3 (from autosub)
  Using cached progressbar-2.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/yf/q0zr3n9s33q_y9rtsnfdnrzh0000gn/T/pip-build-l9c_ljng/progressbar/setup.py", line 5, in <module>
        import progressbar
      File "/private/var/folders/yf/q0zr3n9s33q_y9rtsnfdnrzh0000gn/T/pip-build-l9c_ljng/progressbar/progressbar/__init__.py", line 59, in <module>
        from progressbar.widgets import *
      File "/private/var/folders/yf/q0zr3n9s33q_y9rtsnfdnrzh0000gn/T/pip-build-l9c_ljng/progressbar/progressbar/widgets.py", line 121, in <module>
        class FileTransferSpeed(Widget):
      File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/abc.py", line 133, in __new__
        cls = super().__new__(mcls, name, bases, namespace)
    ValueError: 'format' in __slots__ conflicts with class variable
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/yf/q0zr3n9s33q_y9rtsnfdnrzh0000gn/T/pip-build-l9c_ljng/progressbar/
```

Could this have something to do with the latest 3.6 release?

**Comment by Hasanajouz** [comment]
me too i faced this problem 
i have python 3.6
and i tried to install it today

**Comment by tlkahn** [comment]
Same ask. Is this repo still maintained?

**Comment by intcreator** [comment]
I'm on macOS Sierra which I believe uses Python 2 and I'm still getting this error.

**Comment by hlcb91** [comment]
```
wget https://pypi.python.org/packages/5b/45/e404d9482ec6d584e34a4d24ebb2377486ccd17887515bff38fa521d6619/autosub-0.3.11.tar.gz
tar -xvf autosub-0.3.11.tar.gz
rm -f autosub-0.3.11.tar.gz
sed -i "s/'progressbar>=2.3'/'progressbar>=2.3;python_version<\"3.0\"',\n        'progressbar33>=2.4;python_version>=\"3.0\"'/" autosub-0.3.11/setup.py
tar -cvzf autosub-0.3.11.tar.gz autosub-0.3.11
rm -rf autosub-0.3.11
python3 -m pip install autosub-0.3.11.tar.gz
```

**Comment by jojonki** [comment]
I faced this error with python 3.6. So I tried with python 2.6. It succeeded. I think applicable python version should be written in ReadMe.
