### ISSUE TITLE
Does not find video

### ISSUE THREAD

**Issue by richardpenman** [agermanidis/autosub#5]
```bash
$ sudo pip install autosub
$ ls
test.avi
$ autosub --format=srt -C 2 -S en-US -D en -o test.srt test.avi
Traceback (most recent call last):
  File "/usr/local/bin/autosub", line 256, in <module>
    sys.exit(main())
  File "/usr/local/bin/autosub", line 193, in main
    audio_filename, audio_rate = extract_audio(args.source_path)
  File "/usr/local/bin/autosub", line 103, in extract_audio
    subprocess.check_output(command)
  File "/usr/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
$ autosub test.avi
Traceback (most recent call last):
  File "/usr/local/bin/autosub", line 256, in <module>
    sys.exit(main())
  File "/usr/local/bin/autosub", line 193, in main
    audio_filename, audio_rate = extract_audio(args.source_path)
  File "/usr/local/bin/autosub", line 103, in extract_audio
    subprocess.check_output(command)
  File "/usr/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by agermanidis** [comment]
Do you have ffmpeg installed?



—

**Comment by agermanidis** [comment]
I'm assuming that not having ffmpeg installed was the issue so I'm closing this. If it wasn't do let me know!

**Comment by richardpenman** [comment]
ah yes, that was the problem. Perhaps could replace ffmpeg subprocess call with something like this:

```python
try:
        subprocess.check_output(command)
except OSError as e:
        print 'Please install ffmpeg'
        raise e
```
