### ISSUE TITLE
ImportError: No module named constants

### ISSUE THREAD

**Issue by andyou123** [agermanidis/autosub#60]
I have this error. Can anyone help me? I tried to uninstall and reinstall autosub many times but not still not working. Thank you!

Traceback (most recent call last):
  File "C:\Python27\Scripts\autosub_app.py", line 17, in <module>
    from autosub.constants import LANGUAGE_CODES
  File "C:\Python27\Scripts\autosub.py", line 17, in <module>
ImportError: No module named constants

File "constants.py" was already in "lib" folder.

Please help me. Thank you so much!

**Comment by arminkhosro** [comment]
I had the same issue. I just downloaded the constants.py (in section code) and saved it in the same folder as the autosub_app.py
