### ISSUE TITLE
Error Installing autosub

### ISSUE THREAD

**Issue by shefik** [agermanidis/autosub#65]
Error when running the install command `pip install autosub`

```
Collecting autosub
  Using cached autosub-0.3.12.tar.gz
Collecting google-api-python-client>=1.4.2 (from autosub)
  Using cached google_api_python_client-1.6.2-py2.py3-none-any.whl
Collecting requests>=2.3.0 (from autosub)
  Using cached requests-2.18.1-py2.py3-none-any.whl
Collecting pysrt>=1.0.1 (from autosub)
  Using cached pysrt-1.1.1.tar.gz
Collecting progressbar>=2.3 (from autosub)
  Using cached progressbar-2.3.tar.gz
Collecting six<2dev,>=1.6.1 (from google-api-python-client>=1.4.2->autosub)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting httplib2<1dev,>=0.9.2 (from google-api-python-client>=1.4.2->autosub)
  Using cached httplib2-0.10.3.tar.gz
Collecting uritemplate<4dev,>=3.0.0 (from google-api-python-client>=1.4.2->autosub)
  Using cached uritemplate-3.0.0-py2.py3-none-any.whl
Collecting oauth2client<5.0.0dev,>=1.5.0 (from google-api-python-client>=1.4.2->autosub)
  Using cached oauth2client-4.1.2-py2.py3-none-any.whl
Collecting urllib3<1.22,>=1.21.1 (from requests>=2.3.0->autosub)
  Using cached urllib3-1.21.1-py2.py3-none-any.whl
Collecting idna<2.6,>=2.5 (from requests>=2.3.0->autosub)
  Using cached idna-2.5-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests>=2.3.0->autosub)
  Using cached certifi-2017.4.17-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.3.0->autosub)
  Using cached chardet-3.0.4-py2.py3-none-any.whl
Collecting rsa>=3.1.4 (from oauth2client<5.0.0dev,>=1.5.0->google-api-python-client>=1.4.2->autosub)
  Using cached rsa-3.4.2-py2.py3-none-any.whl
Collecting pyasn1-modules>=0.0.5 (from oauth2client<5.0.0dev,>=1.5.0->google-api-python-client>=1.4.2->autosub)
  Using cached pyasn1_modules-0.0.9-py2.py3-none-any.whl
Collecting pyasn1>=0.1.7 (from oauth2client<5.0.0dev,>=1.5.0->google-api-python-client>=1.4.2->autosub)
  Using cached pyasn1-0.2.3-py2.py3-none-any.whl
Installing collected packages: six, httplib2, uritemplate, pyasn1, rsa, pyasn1-modules, oauth2client, google-api-python-client, urllib3, idna, certifi, chardet, requests, pysrt, progressbar, autosub
  Found existing installation: six 1.4.1
    DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling six-1.4.1:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/var/folders/nf/n6bqf42169s8n0q3669609n40000gn/T/pip-kmtfhQ-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'
```

**Comment by shefik** [comment]
Running this command on Mac appeared to work instead, without throwing an error. Please update your docs.

Refs https://github.com/agermanidis/autosub/issues/36

**Comment by saruvij** [comment]
Am still not able to install. Same error. Any guess?

**Comment by zefangzh** [comment]
Am still not able to install. Same error. Any guess?
