### ISSUE TITLE
python27 software Permission denied issues

### ISSUE THREAD

**Issue by newbie1991** [agermanidis/autosub#70]
Hello I am hearing impaired and uses subtitles or closed captioned (CC) for videos  watching. Some videos don't have subtitles or CC on them. I found this interesting pyhton 27 software that automatically makes subtitles in videos.  I understand that the video format for this to work is in MP4 only.  I thought I had everything I need to have to make this video subtitles to work.  However, according to the Windows command process, I have found the following errors:

Using windows 10 operating system 32-bit and Firefox browser.

  Python27 scripts autosub flac permission denied                                           

C:\Users\d\Desktop>C:\Python27\python.exe C:\Python27\scripts\autosub_app.py -C 2 -S en -D en C:\Users\d\Desktop\EnglishObama.mp4
c:\users\d\appdata\local\temp\tmpyubnxz.flac: Permission denied| ETA:  --:--:--
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Python27\lib\multiprocessing\pool.py", line 389, in _handle_results
    task = get()
TypeError: ('__init__() takes at least 3 arguments (1 given)', <class 'subprocess.CalledProcessError'>, ())

c:\users\d\appdata\local\temp\tmp4boeti.flac: Permission denied
c:\users\d\appdata\local\temp\tmpo75t4d.flac: Permission denied
c:\users\d\appdata\local\temp\tmpwnksga.flac: Permission denied
c:\users\d\appdata\local\temp\tmpqg3ifz.flac: Permission denied
c:\users\d\appdata\local\temp\tmpdswmie.flac: Permission denied
c:\users\d\appdata\local\temp\tmpbf5ixl.flac: Permission denied
c:\users\d\appdata\local\temp\tmpau41p2.flac: Permission denied
c:\users\d\appdata\local\temp\tmpzxgemy.flac: Permission denied
c:\users\d\appdata\local\temp\tmpmsuagn.flac: Permission denied
c:\users\d\appdata\local\temp\tmpe_64dy.flac: Permission denied
c:\users\d\appdata\local\temp\tmptsapsp.flac: Permission denied
c:\users\d\appdata\local\temp\tmpdwdl8y.flac: Permission denied
c:\users\d\appdata\local\temp\tmpzp1okl.flac: Permission denied
c:\users\d\appdata\local\temp\tmp1mp76j.flac: Permission denied
c:\users\d\appdata\local\temp\tmpnhiafl.flac: Permission denied
c:\users\d\appdata\local\temp\tmppkqsqc.flac: Permission denied
c:\users\d\appdata\local\temp\tmppcfouo.flac: Permission denied
c:\users\d\appdata\local\temp\tmpwtpw2m.flac: Permission denied
c:\users\d\appdata\local\temp\tmp6puagf.flac: Permission denied
c:\users\d\appdata\local\temp\tmpubgdua.flac: Permission denied
c:\users\d\appdata\local\temp\tmpxuftxp.flac: Permission denied
c:\users\d\appdata\local\temp\tmp9_geaj.flac: Permission denied
c:\users\d\appdata\local\temp\tmp9qu6ej.flac: Permission denied
c:\users\d\appdata\local\temp\tmp5lemmm.flac: Permission denied
c:\users\d\appdata\local\temp\tmprzifh5.flac: Permission denied
c:\users\d\appdata\local\temp\tmp_ndctx.flac: Permission denied
c:\users\d\appdata\local\temp\tmp1srgv_.flac: Permission denied
c:\users\d\appdata\local\temp\tmpyuolrh.flac: Permission denied
c:\users\d\appdata\local\temp\tmpk60oep.flac: Permission denied
c:\users\d\appdata\local\temp\tmpr8pma8.flac: Permission denied
c:\users\d\appdata\local\temp\tmpv_4z00.flac: Permission denied
c:\users\d\appdata\local\temp\tmp0unmgn.flac: Permission denied

I am a newbie at this. I followed the comments in regards to these issues. However, I am lost as to how to repair/resolve the problems above.. I would like to know how to resolve these issues to make this subtitles work using simple understanding step by step process.  Any help out there is greatly appreciated.

**Comment by newbie1991** [comment]
I finally resolved the issue. I did not saved the modiied script (txt. file) in the autosub correctly to the py file format . I was abled to play the sample file with autosubs and works great. Thanks for all the help in this forum.
