### ISSUE TITLE
'module' object has no attribute 'exceptions'

### ISSUE THREAD

**Issue by darkzbaron** [agermanidis/autosub#71]
python.exe autosub_app.py -S en -D en "C:\Users\Jonathan\Downloads\SampleVideos.Spanish.-.English\EnglishObama.mp4"
Converting speech regions to FLAC files: 100% |#################| Time: 0:00:01
Traceback (most recent call last):% |                          | ETA:  --:--:--
  File "autosub_app.py", line 283, in <module>
    sys.exit(main())
  File "autosub_app.py", line 231, in main
    for i, transcript in enumerate(pool.imap(recognizer, extracted_regions)):
  File "apps\Python27\lib\multiprocessing\pool.py", line 668, in next
    raise value
AttributeError: 'module' object has no attribute 'exceptions'

Anyone has the same issue? Losing my hairs on this!

**Comment by darkzbaron** [comment]
probably something wrong with my Python install. I ran in a clean venv and it works fine. Thanks!
