### ISSUE TITLE
Erro Install autossub 

### ISSUE THREAD

**Issue by boubli** [agermanidis/autosub#90]
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/md/qs2sj3q52qv9h4xjvtp_66bw0000gn/T/pip-install-6yo738md/progressbar/

**Comment by jenslauterbach** [comment]
I get the same error:

```
Collecting autosub
  Using cached https://files.pythonhosted.org/packages/f3/31/d3d677e97ec3e24ae6131df91eb5d20650309e3ed5122361613792180fb7/autosub-0.3.12.tar.gz
Collecting google-api-python-client>=1.4.2 (from autosub)
  Using cached https://files.pythonhosted.org/packages/0e/7b/0adbc5ee668e9006422c38ee6b7b92c018b03839fc7a11b18cc51054e88b/google_api_python_client-1.6.6-py2.py3-none-any.whl
Collecting requests>=2.3.0 (from autosub)
  Using cached https://files.pythonhosted.org/packages/49/df/50aa1999ab9bde74656c2919d9c0c085fd2b3775fd3eca826012bef76d8c/requests-2.18.4-py2.py3-none-any.whl
Collecting pysrt>=1.0.1 (from autosub)
  Using cached https://files.pythonhosted.org/packages/f6/33/16ad65a8973cb8bcb494af09ee1b9ab5ffdd6ff300bce5d3ac7d3cb1f2cc/pysrt-1.1.1.tar.gz
Collecting progressbar>=2.3 (from autosub)
  Using cached https://files.pythonhosted.org/packages/0f/e1/f30b72ecabba259c7c38dd0eb944a173effced3fd7de2c9c2902bd6f649a/progressbar-2.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/xc/s0vn39m13lx1s4dcq4mx0kw00000gn/T/pip-install-i4csglhi/progressbar/setup.py", line 5, in <module>
        import progressbar
      File "/private/var/folders/xc/s0vn39m13lx1s4dcq4mx0kw00000gn/T/pip-install-i4csglhi/progressbar/progressbar/__init__.py", line 59, in <module>
        from progressbar.widgets import *
      File "/private/var/folders/xc/s0vn39m13lx1s4dcq4mx0kw00000gn/T/pip-install-i4csglhi/progressbar/progressbar/widgets.py", line 121, in <module>
        class FileTransferSpeed(Widget):
      File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/abc.py", line 133, in __new__
        cls = super().__new__(mcls, name, bases, namespace, **kwargs)
    ValueError: 'format' in __slots__ conflicts with class variable

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/xc/s0vn39m13lx1s4dcq4mx0kw00000gn/T/pip-install-i4csglhi/progressbar/```

Environment:

1. MacOS 10.3.3
2. Python 3.6.4
3. Pip 10.0.1

**Comment by SilentGene** [comment]
I got the same error.
win10
python3.6

**Comment by tlan16** [comment]
I got the same error on Ubuntu. Here's the work around:
```bash
git clone https://github.com/agermanidis/autosub.git
cd autosub
python2 setup.py install --user
autosub -h
```
