### ISSUE TITLE
A problem on mac

### ISSUE THREAD

**Issue by BurstLee** [agermanidis/autosub#97]
BurstdeMacBook-Air:~ burst$ /Users/burst/Desktop/autosub ; exit;
Traceback (most recent call last):
  File "/Users/burst/Desktop/autosub", line 303, in <module>
    sys.exit(main())
  File "/Users/burst/Desktop/autosub", line 184, in main
    parser = argparse.ArgumentParser()

I have not studied pyhon.
I need someone to help me.
thx

**Comment by SuperElephant** [comment]
It may be caused by the wrong arguments you put in.
you should input like this:
`<path to autosub> <path to your video>`
eg. for me it would be:
`/usr/local/bin/autosub /Users/cx/Downloads/Ashton_Building.mp3`

BTW if there is any information provided after words like "Exception:" , "error", it would be much helpful.
